# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-f604be6d-6d37-4ae8-ac95-23068fefc2e7";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."luks-f604be6d-6d37-4ae8-ac95-23068fefc2e7".device = "/dev/disk/by-uuid/f604be6d-6d37-4ae8-ac95-23068fefc2e7";

  fileSystems."/nix" =
    { device = "/dev/mapper/luks-f604be6d-6d37-4ae8-ac95-23068fefc2e7";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/4BE0-8811";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/6b97c85a-ab13-4e25-8fcb-8c394eb1a981";
      fsType = "btrfs";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/24c84c35-4329-4da6-8798-bf09a7211c77"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
