# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "usb_storage"
    "usbhid"
    "sd_mod"
    "sdhci_pci"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-6effd931-cda3-4e60-8a3e-c28f6fc724e5";
    fsType = "btrfs";
  };

  boot.initrd.luks.devices."luks-6effd931-cda3-4e60-8a3e-c28f6fc724e5".device =
    "/dev/disk/by-uuid/6effd931-cda3-4e60-8a3e-c28f6fc724e5";

  fileSystems."/nix" = {
    device = "/dev/mapper/luks-6effd931-cda3-4e60-8a3e-c28f6fc724e5";
    fsType = "btrfs";
    options = [ "subvol=nix" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/D5A4-6A22";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/2b17ec4a-f7c8-41e0-81bd-1eac2916567d";
    fsType = "btrfs";
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/911e6712-7bf4-4958-bac7-0096719d90ef"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
