# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-9bd908ee-c98d-4b89-a1cf-f0a17c3cb00e";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."luks-9bd908ee-c98d-4b89-a1cf-f0a17c3cb00e".device = "/dev/disk/by-uuid/9bd908ee-c98d-4b89-a1cf-f0a17c3cb00e";

  fileSystems."/nix" =
    { device = "/dev/mapper/luks-9bd908ee-c98d-4b89-a1cf-f0a17c3cb00e";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/1563-9E84";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/c0293aa1-1e7c-4870-80a0-80c07bc7c7bd";
      fsType = "btrfs";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/ad100b99-19be-49e9-9540-9f64549021b4"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
